### ISSUE TITLE
[Virtualbox] linked clone leads to ghost VM on Linux

### ISSUE THREAD

**Issue by sysarcher** [AntonioMeireles/ClearLinux-packer#6] opened 2018-07-09 14:43 UTC
We are doing [`vbox.linked_clone = true`](https://github.com/AntonioMeireles/ClearLinux-packer/blob/fb3d2f7653d42c3ce0039827f5d10f14256616ad/Vagrantfile#L36) which leads to a ghost VM (which inherits its name from the [`Makefile`](https://github.com/AntonioMeireles/ClearLinux-packer/blob/master/Makefile#L1))

This leaves VMs behind even after a `vagrant destroy` command.

**Comment by AntonioMeireles** [comment] 2018-07-09 14:46
humm, good catch. not using primarily vbox here, so that slipped away ... other than turning linked_clones to false on vbox do you have any idea / suggestion on how to fix this ? (i'll dig on my side anyway :-) ) 

And thanks, once again, for reporting!

**Comment by sysarcher** [comment] 2018-07-09 14:49
You can just omit the line with `linked_clone = true` and let the user decide in _his_ `Vagrantfile` whether he wants to do Linked Clones.

Thank YOU for maintaining the only working Clearlinux box 👍

**Comment by sysarcher** [comment] 2018-07-09 14:53
I would similarly [not force a name](https://github.com/AntonioMeireles/ClearLinux-packer/blob/master/Vagrantfile#L35) because `vagrant up` inherits a default name from the path of the Vagrantfile. This way (hopefully) you can run multiple instances of clearlinux by having multiple Vagrantfiles in different folders. 

What do you think?

**Comment by AntonioMeireles** [comment] 2018-07-09 14:56
will look at it deeply- as soon as i get an hole in my schedule. i run regularly (with fusion) several k8s nodes without issues. fwiw, and for context, i developed this to help simulate k8s deployments on top of CL.

**Comment by sysarcher** [comment] 2018-07-09 15:21
@AntonioMeireles oh nice.. k8s FTW!!

**Comment by AntonioMeireles** [comment] 2018-07-10 11:09
@shrmrf 

`23610` boxes are available and stopped hardcoding default box name. 
regarding the `linked_clone` issue i'm still digging to grasp it fully. (should have quality time for this, at worst, tomorrow, hopefully)

**Comment by sysarcher** [comment] 2018-07-18 09:09
Hi @AntonioMeireles did you get a chance to look into the `linked_clone` thing?

**Comment by AntonioMeireles** [comment] 2018-07-18 09:14
yes, but sadly without concrete results :-/ yet ... trying to find the right solution ... (not too fond of just disabling `linked_clone` for VBox, as it gets things way slower and burns way too much stuff, specially when people play with test clusters)

**Comment by sysarcher** [comment] 2018-07-18 09:36
According to [the docs](https://www.vagrantup.com/docs/virtualbox/configuration.html#linked-clones) having `linked_clone = false` _is_  supposed to be the default behavior. 

The users can then choose to set `linked_clone = true` in their `Vagrantfile`. Sadly I am unable (at least for a few more days) to test if that'd leave a ghost VM behind. I'm thinking that it won't!!

**Comment by AntonioMeireles** [comment] 2018-07-18 09:39
humm, when using `linked_clone = true` did you also ever got ghost VMs leftovers in boxes other than this one ? (i.e. is this a general _misfeature_ of current upstream VBox/vagrant combo or not sure ?)

**Comment by sysarcher** [comment] 2018-07-18 09:40
@AntonioMeireles I only found out about the `linked_clone` feature after going through your code. You introduced me to it and I only have theoretical/clerical knowledge.

**Comment by sysarcher** [comment] 2018-07-19 12:45
@AntonioMeireles I got a chance to see if `linked_clone` has the same behavior on `ubuntu/bionic64`. It does. I explicitly enabled `linked_clone = true` and it also left behind a ghost VM that vagrant isn't able to manage.

**Comment by AntonioMeireles** [comment] 2018-07-19 13:36
Ok, *thanks!*, the picture is getting fuller :-) One more question -  the _ghost VMs_ that are left behind are actually (left) on disk or are just cruft referenced in the "Oracle VM VirtualBox Manager" and marked there as "Inaccessible" ?

Thanks again for your patience!

**Comment by sysarcher** [comment] 2018-07-19 22:09
Hi @AntonioMeireles 

I'm pasting the results of `vboxmanage list vms` below. It seems to me that `ClearLinux_1531988462211_88806` is the VM that's first created using the vagrant box and all further Clearlinux VMs will be link-cloned from it.

```
$ vboxmanage list vms
"ClearLinux_1531988462211_88806" {a1640939-e596-4bfa-bfbd-7cb73c63ce30}
"ClearLinux" {62e6577a-887f-4edb-8ae9-6719df59b565}
"ubuntu-bionic-18.04-cloudimg-20180717_1532004133598_38556" {f83f61da-06f8-41ee-90c8-c69bdc1cac9c}
```

Above, I've already deleted my ubuntu machine using `vagrant destroy`

### Snapshots
Here is the output of the `snapshot` option in `vboxmanage`.
```
$ vboxmanage snapshot "ClearLinux_1531988462211_88806" list
   Name: base (UUID: 67d6d6ac-619e-4c53-a8d6-f768981cc767) *
```

```
$ vboxmanage snapshot "ubuntu-bionic-18.04-cloudimg-20180717_1532004133598_38556" list
   Name: base (UUID: 1476c0a9-2284-4cda-8bb5-2242f3addf3b) *
```

These are being used as base for newer instances.

**Comment by AntonioMeireles** [comment] 2018-07-23 09:21
@shrmrf 

OK, here's my thoughts so far ... 
- from a UI perspective the behaviour you found under VBox it's clearly undesirable and unexpected
- AFAICT that behaviour, being induced by our use of the `linked_clone` feature, is not specific at all to us
- OTOH, IMHO the gains we achieve (space savings and performance wise) by using the `linked_clone` feature specially when simulating whole clusters can't be neglected also. 

So, it all ends what is more important - performance, and space savings (i.e. keeping on VBox `linked_clone = true`, **and** having the periodically, when using VBox, to clean some leftovers manually ... or not having at all to do the later ? (by flipping `linked_clone = false` by default under VBox) ?

So, i'm very undecided on what's the *right* trade-off ? @kvietmeier any thoughts on this, too? (as you're an heavy VBox user too)

**Comment by sysarcher** [comment] 2018-07-23 09:56
Hey Antonio, thanks for the summary. 

I think `linked_clone = false` in the Vagrantfile shipped to _all_ users is the right behavior. This way, the Clearlinux box would feel more like any other _official_ distro's box. 

If someone wants the `linked_clone` behavior, they can do so explicitly in their `Vagrantfile` like I did for the Ubuntu box.

The decision is up to you to make :) Now that i understand the cause of this extra VM on my machine, I don't mind it too much.

**Comment by kvietmeier** [comment] 2018-07-25 00:32
I have noticed this and I just delete them after I'm done working with CL.   To be honest I'm thinking about enabling it in my other Vagrantfiles because it is a bit quicker to spin up the second and third VM and I have 2 multi-machine environments for Ceph and K8S.  I do think it is mildly irritating but mostly cosmetic.  I just issue a "vboxmanage unregistervm <ID> --delete".   Now I just need to find the Powershell equiv to "vboxmanage list vms | grep -i clearlinux | awk ..... | xargs ....   :)   I do feel that it may be better to stick with the conventional behaviour of boxes and not enable the linked clone.   Allowing the end user to choose to do so.  Now that I know how it works, I will probably enable when iterating a bunch of times.   
HTH
Karl V.

**Comment by sysarcher** [comment] 2018-07-25 09:55
@kvietmeier I don't know if you already knew about this (and I don't have a powerful enough Windows machine to test with Virtualbox...)

In powershell you have `Select-String` which replaces `grep` and perhaps what you want to do with `awk` here is a `%{$_.Split(' ')[1];}` operation... (hope I was helpful)

**Comment by AntonioMeireles** [comment] 2018-07-25 10:07
ok, 

the issue is actually referenced, in the official upstream docs, [here](
https://www.vagrantup.com/docs/virtualbox/configuration.html#linked-clones) so, in that sense it's not a bug, it's a VBox Vagrant plugin _"feature"_.

Given that `linked_clone` is not the default under VBox i just turned it off by default there. New boxes with the _fix_ in a  bit.

OTOH, it is the [default](
https://www.vagrantup.com/docs/vmware/configuration.html#linked-clones) with the VMware provider (which i use heavily) and AFAICT it has no nefarious side effects in that front, so i'll leave it as-is now in the VMware side. 

P.S. you guys know that these days you can now use `bash` & associates on windows, right ;-) ?

**Comment by AntonioMeireles** [comment] 2018-07-25 10:39
**closing** as **[23940](https://app.vagrantup.com/AntonioMeireles/boxes/ClearLinux/versions/23940)**, that just got out,  consumes the fix :-) 

please reopen if unexpected _surprises_ arise.

And **thanks** you all for your patience!

**Closed as completed by AntonioMeireles** 2018-07-25 10:39 UTC

**Comment by sysarcher** [comment] 2018-07-25 11:02
I have `bash` enabled on my windows machines but don't know if I can launch virtualbox from in there... must check it out!!

Thanks for the fix!!! I'll try it out asap

**Comment by sysarcher** [comment] 2018-07-25 11:52
@AntonioMeireles Works perfectly!!!

Thanks again!!

**Comment by kvietmeier** [comment] 2018-07-25 14:10
I have the WSL installed but I have commited to Powershell to force myself to learn it.   Now that there is an OpenSSH port to PS I have everything I need, haven't used WSL for a while.   Like bash, with a little work on your profile.ps1 PS becomes very usable.  I even have it setup to detect whether I'm on my corp network and set proxies appropriately - for Vagrant too.
[https://github.com/kvietmeier/scripts/blob/master/powershell/MyProfile.ps1](url)
